- .github/workflows/actions-compile.yml
Any contribution should compile on Ubuntu.
> Add a first basic check of compilation

- Makefile
- README.md
- lib/Makefile
- src/Makefile
Since clang is pretty aggressive, it allows to detect some weird cases such as:
```
gtp_ppp.c:1994:14: warning: implicit conversion from 'int' to 'char' changes value from 129 to -127 [-Wconstant-conversion]
opt[i++] = IPCP_OPT_PRIMDNS;
~ ^~~~~~~~~~~~~~~~
include/gtp_ppp.h:65:26: note: expanded from macro 'IPCP_OPT_PRIMDNS'
#define IPCP_OPT_PRIMDNS        129     /* primary remote dns address */
^~~
```
TODO: if this pull request is accepted, I will (1) try to fix the issues raised by clang and then (2) extend the compilation tests to run with both gcc and clang.
> add clang support along with gcc

- .github/workflows/actions-compile.yml
Since clang can be quite agressive for some checks, let's try both compilations.
references:
https://levelup.gitconnected.com/utilizing-github-actions-to-build-and-test-on-multiple-platforms-a7fe3aa6ce2a
https://docs.github.com/en/actions/using-workflows/about-workflows#using-a-matrix
> test compilation with both gcc and clang

- README.md
set the listening ports
The number of listener is set at compilation time. Later on, it'll be changeable using listener-count argument:
gtpc-tunnel-endpoint 0.0.0.0 port 2123 listener-count 1
gtpu-tunnel-endpoint 0.0.0.0 port 2152 listener-count 1
currently, it is only valid for gtpc but note that write terminal will not restore this value.
> README: few notes to enable GTPu and GTPc

- README.md
- src/gtp_router_vty.c
- src/gtp_switch_vty.c
- src/gtp_vrf_vty.c
- src/include/gtp_vty.h
Tune the number of workers (pthreads).
> set listener count: for GTPc, GTPu and PPPoE workers

- README.md
- src/main.c
Run GTP_GUARD_PID_FILE=/tmp/gtp.pid bin/gtp-guard args... in order to to define an alternate file. It can be useful on Docker environment or others when /var/run shall not be used.
I will need it in order to run gtp-guard with some gtping tests using github's Actions.
> Alternate file for /var/run/gtp-guard.pid / getenv

- src/Makefile
- src/bpf/Makefile
XXX: there are many different schools about compiling or not with Werror ; what's about your take on it ?
Since all the warnings are sanitized, let's stop the compilation on any warning. The main benefit is when the github actions are running, they'll stop during the checks of a pull request.
> make: CFLAGS with Werror

- .github/workflows/actions-compile.yml
XXX do not merge
Thanks to:
https://github.com/ThomasHabets/gtping
target:
- run gtp-guard per README.md's configuration file
- gtping -c 3 128.0.0.1 -t 100 # should be ok
It cannot work yet since the former pull request is needed in order to set the pid file because we have the following constraint with github's action:
```
gtp-guard: pidfile_write : Can not open /var/run/gtp-guard.pid pidfile
```
> Draft: Checks using gtping

- .github/workflows/actions-compile.yml
thanks to the former commits, it is now possible to have a complete test up to a GTP ping.
see: https://github.com/vjardin/gtp-guard/actions/runs/7884666695/job/21514178321
TBD: how to have a GTPu ping ?
> fix gtp-guard pipeline using gtping

- .github/workflows/actions-compile.yml
- test/testenv.sh
let's have a simpler workflow and let's have the ability to run the tests on our local setup too.
For the records, see: https://github.com/vjardin/gtp-guard/actions/runs/7906617454/job/21581891672#step:4:287
Note: it is broken on the head, since eBPF PPP is having the following issue:
https://github.com/vjardin/gtp-guard/actions/runs/7906684774/job/21582126747#step:4:232
```
[...]
libbpf: map 'teid_ingress': found map_flags = 1.
libbpf: map 'ppp_ingress': at sec_idx 6, offset 120.
libbpf: map 'ppp_ingress': can't determine key size for type [30]: -22.
ERROR: opening BPF object file failed
```
next: add GTPu ping, enable the gtp_mirror.bpf which is currently disabled.
> test: run locally and on github's runner, include eBPF checks

- src/bpf/gtp_route.c
fix for:
[...]
libbpf: map 'teid_ingress': found map_flags = 1.
libbpf: map 'ppp_ingress': at sec_idx 6, offset 120.
libbpf: map 'ppp_ingress': can't determine key size for type [30]: -22.
ERROR: opening BPF object file failed
note: it was detected by testenv.sh (see the pull request !15)
> gtp_route: fix eBPF load error

- Makefile
Till now, we add to compile the eBPF module independently of gtp-guard, what's about including its compilation too ?
TODO: if it is approve and merge, it means that we should update the github's workflow that was taking care of this standalone compilation too.
> eBPF: include its compilation

- .github/workflows/actions-compile.yml
This action can be removed from the workflow since make all does the job since the commit a8b0df8288f
> minor: ebpf modules are already compiled

- test/testenv.sh
test using bpftool, example of check:
https://github.com/vjardin/gtp-guard/actions/runs/7924514635/job/21636224232#step:4:382
the purpose is to have the validation from the kernel's verifier.
It is not a unit test using bpftool prog run:
```
bpftool prog run PROG data_in FILE [data_out FILE [data_size_out L]] [ctx_in FILE [ctx_out FILE [ctx_size_out M]]] [repeat N]
```
> test gtp_mirror.bpf

- Makefile
- src/bpf/Makefile
Add support to any target folder, the main purpose is to support packages such as Buildroot ones.
Let's be a bit verbose on clang and llc that are selected since it can become complex to debug.
> Verbose bpf + allow define-able prefix

- README.md
Cosmetic update about the target bpf files which are into the bin/ folder instead of src/bpf.
> README: all bpf are into bin/

- README.md
- test/gtpguardjson.py
This commit introduces a basic Python script that leverages the JSON-based interface documented in doc/json.md. It can serve as a foundation for extending gtp-guard monitoring and establishing a telemetry framework.
> json monitoring: add Python example script

- src/gtp_pppoe.c
The daemon does not quit in case of a SIGTERM when a PPPoE session is established but there is no PPPOE signaling traffic.
We can notice that it keeps blocking on recvmmsg() syscall:
```
[pid 262269] recvmmsg(46,  <unfinished ...>
[pid 262268] recvmmsg(44,  <unfinished ...>
[pid 262264] recvmmsg(43,  <unfinished ...>
```
Those fd are:
```
gtp-guard 262250 root   43u     pack            4610713      0t0 PPP_SES type=SOCK_RAW
gtp-guard 262250 root   44u     pack            4641817      0t0 PPP_DIS type=SOCK_RAW
gtp-guard 262250 root   46u     pack            4629533      0t0 PPP_SES type=SOCK_RAW
```
> fix PPPOE SIGTERM

- lib/signals.c
- src/main.c
Remove the runtime logs:
```
gtp-guard[264013]: sigaction failed for signalfd
```
Meanwhile the log is updated in order to get the signal id:
```
gtp-guard[264472]: sigaction failed for signo 9
```
> cosmetic - no signal handler for SIGKILL

- src/gtp_pppoe_proto.c
Cosmetic fix of:
```
pppoe2: pppoe brd filtering...  s->pppoe->ifindex(20)!=pppoe->ifindex(21) for ff:ff:ff:ff:ff:ff session = 0x0000pppoe1: pppoe hunique:0x15e44444 session:0x1122 hw:xx:xx:xx:xx:xx:xx connected
```
> pppoe debug: add missing end of line

- src/gtp_conn.c
- src/gtp_htab.c
- src/include/gtp_htab.h
refcnt is not needed in dlock_mutex struct, because lock is always kept hold while this refcnt is updated.
remove it and simplify code.
> dlock: remove unused refcnt

- src/gtp_switch_hdl_v1.c
During delete PDP context request handling the serving node must be updated to forward the delete PDP context request to the PGW. Without this fix the message is forwarded to the last serving node which contacted GTP-Guard.
> GTPv1: fix update of the serving node in delete PDP context request handler
